version: 2.1

orbs: 
  node: circleci/node@5.0.2 

jobs:
  install-node:
    steps:
      - checkout
      - node/install:
          node-version: 14.17.0
          install-yarn: true
      - run:
          name: Check node version
          command: node --version
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: sudo npm install -g npm@latest
      - run: npm run test
      - node/run:
          npm-run: build

workflows:
  build:
    jobs:
      - install-node