version: 2.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
  build-workflow:
    jobs:
      - say-hello
  test-workflow:
    jobs:
      - say-hello
  deploy-workflow:
    jobs:
      - say-hello