version: 2.1

orbs: 
  node: circleci/node@5.0.2 

jobs:
  install-node:
    steps:
      - checkout
      - node/install-packages:
            pkg-manager: npm
        - run:
            command: npm run test
            name: Run tests
        - run:
            command: npm run build
            name: Build app
        - persist_to_workspace:
            root: ~/project
            paths:
              - .

workflows:
  build:
    jobs:
      - install-node