version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
workflows:
  build-workflow:
    jobs:
      - build
  test-workflow:
    jobs:
      - build
  deploy-workflow:
    jobs:
      - build