version: 2.1

orbs: 
  node: circleci/node@5.0.2 

workflows:
  test:
    jobs:
      - node/test:
          version: 14.17.0
          steps:
            - checkout
            - run: npm install
            - run: npm run test
