version: 2.1

orbs: 
  node: circleci/node@5.0.2 

jobs:
  install-node:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: 14.17.0
          install-yarn: true
      - run: node --version
      - node/test:
          name: 'Run tests'
          command: npm test

workflows:
  test:
    jobs:
      - install-node